FCamara-Test/Models/DependenteFuncionario.cs
using System;

namespace FCamara_Test.Models
{
    public class DependenteFuncionario : Entidade
    {
        public string Nome { get; set; }
        public string CPF { get; set; }
        public DateTime DataNascimento { get; set; }
        public string Sexo { get; set; }
        public Guid FuncionarioId { get; set; }

        public virtual Funcionario Funcionario { get; set; }
    }
}

FCamara-Test/Models/Entidade.cs
using System;

namespace FCamara_Test.Models
{
    public class Entidade
    {
        public Guid Id { get; set; }
        public bool Ativo { get; set; }
        public DateTime DataCadastro { get; set; }
        public DateTime? DataAtualizacao { get; set; }
    }
}

FCamara-Test/Models/Funcionario.cs
using System;
using System.Collections.Generic;

namespace FCamara_Test.Models
{
    public class Funcionario : Entidade
    {
        public string Nome { get; set; }
        public string CPF { get; set; }
        public DateTime DataNascimento { get; set; }
        public  char Sexo { get; set; }
        public string Cep { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Estado { get; set; }
        public string Cidade { get; set; }

        public virtual ICollection<DependenteFuncionario> DependenteFuncionarios { get; set; }
    }
}

FCamara-Test/Models/HistoricoAuditoria.cs
using System;

namespace FCamara_Test.Models
{
    public class HistoricoAuditoria : Entidade
    {
        // Campo responsavel por quardar o identificador da tabela a ser gravada como historico
        public string Funcionalidade { get; set; }

        // Nome da ação que esta sendo gravada, exemplo (criado,editado,excluido)
        public string Evento { get; set; }

        // Campo onde ira guardar, o json do dado a ser alterado ou criado ou excluido
        public string Dados { get; set; }

        // ID do registro que esta sendo gravado, exemplo (criado,editado,excluido)
        public Guid IdentificadorFuncionalidade { get; set; }
    }
}

FCamara-Test/Controllers/AniversarianteController.cs
using FCamara_Test.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace FCamara_Test.Controllers
{
    public class AniversarianteController : Controller
    {
        private readonly IFuncionarioService _funcionarioService;

        public AniversarianteController(IFuncionarioService funcionarioService)
        {
            _funcionarioService = funcionarioService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public PartialViewResult ListagemAniversariantes(int mes)
        {
            var aniversariantes =  _funcionarioService.ListarAniversariantesMes(mes);
            return PartialView(aniversariantes);
        }
    }
}

FCamara-Test/Controllers/FuncionarioController.cs
using FCamara_Test.Dtos;
using FCamara_Test.Interfaces;
using FCamara_Test.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace FCamara_Test.Controllers
{
    public class FuncionarioController : Controller
    {
        private readonly IFuncionarioService _funcionarioService;

        public FuncionarioController(IFuncionarioService funcionarioService)
        {
            _funcionarioService = funcionarioService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Novo()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Editar(Guid id)
        {
            Funcionario funcionario = _funcionarioService.BuscarPorId(id);

            return View(funcionario);
        }

        [HttpGet]
        public IActionResult NovoDependente(Guid id)
        {
            DependenteFuncionario dependenteFuncionario = new DependenteFuncionario
            {
                FuncionarioId = id
            };

            return View(dependenteFuncionario);
        }

        [HttpGet]
        public IActionResult Excluir(Guid id)
        {
            bool excluido = _funcionarioService.Excluir(id);

            if (excluido)
            {
                return View("ExcluidoComSucesso");
            }

            return View();
        }

        [HttpGet]
        public IActionResult MostrarDependentes(Guid id)
        {
           List<DependenteFuncionario> dependenteFuncionarios = _funcionarioService.TodosDependentesDoFuncionario(id);
            return View(dependenteFuncionarios);
        }

        [HttpGet]
        public IActionResult CadastroFeitoComSucesso()
        {
            return View();
        }

        [HttpGet]
        public IActionResult EditadoComSucesso()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ExcluidoComSucesso()
        {
            return View();
        }

        [HttpPost]
        public PartialViewResult ListagemFuncionarios(FiltroDTO filtroDTO)
        {
            List<Funcionario> funcionarios = _funcionarioService.BuscarPorFiltro(filtroDTO);

            return PartialView(funcionarios);
        }

        [HttpPost]
        public IActionResult CadastrarFuncionario(Funcionario funcionario)
        {
            try
            {
                bool adicionado = _funcionarioService.Adicionar(funcionario);

                if (adicionado)
                {
                    return View("CadastroFeitoComSucesso");
                }

                return View("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Erro = ex.Message;
                return View("Novo");
            }
        }

        [HttpPost]
        public IActionResult EditarFuncionario(Funcionario funcionario)
        {
            bool editado = _funcionarioService.Editar(funcionario);

            if (editado)
            {
                return View("EditadoComSucesso");
            }

            return View("Index");
        }

        [HttpPost]
        public IActionResult CadastrarDependenteFuncionario(DependenteFuncionario dependenteFuncionario)
        {
            try
            {
                bool adicionado = _funcionarioService.AdicionarDependente(dependenteFuncionario);

                if (adicionado)
                {
                    return View("CadastroFeitoComSucesso");
                }

                return View("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Erro = ex.Message;
                return View("NovoDependente");
            }
        }
    }
}

FCamara-Test/Controllers/LogController.cs
using FCamara_Test.Interfaces;
using FCamara_Test.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace FCamara_Test.Controllers
{
    public class LogController : Controller
    {
        private readonly IHistoricoAuditoriaService _historicoAuditoriaService;

        public LogController(IHistoricoAuditoriaService historicoAuditoriaService)
        {
            _historicoAuditoriaService = historicoAuditoriaService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<HistoricoAuditoria> logs = _historicoAuditoriaService.BuscarTodos();

            return View(logs);
        }
    }
}

FCamara-Test/Views/Aniversariante/Index.cshtml
@{
    ViewData["Title"] = "Aniversariantes";
}

<div class="content">

    <h1>Listagem de aniversariantes</h1>

    <div>
        <form>
            <div class="box-form">

                <div class="filtro">

                    <div class="box-campo">
                        <label> Mês</label>
                        <select class="campo-combo" id="mes">
                            <option>Selecione</option>
                            <option value="1">Janeiro</option>
                            <option value="2">Fevereiro</option>
                            <option value="3">Março</option>
                            <option value="4">Abril</option>
                            <option value="5">Maio</option>
                            <option value="6">Junho</option>
                            <option value="7">Julho</option>
                            <option value="8">Agosto</option>
                            <option value="9">Setembro</option>
                            <option value="10">Outubro</option>
                            <option value="11">Novembro</option>
                            <option value="12">Dezembro</option>
                        </select>
                    </div>

                </div>

                <div class="filtro-botao">
                    <div class="conteudo-filtro-botao aniversariantes">
                        <a class="botao" style="padding: 10px;" onclick="buscarAniversariantes()">Buscar</a>
                    </div>
                </div>
            </div>
        </form>
    </div>

    <div id="partialAniversariantes"></div>

</div>

FCamara-Test/Views/Aniversariante/ListagemAniversariantes.cshtml
@model List<FCamara_Test.Dtos.AniversarianteDTO>

<table class="rTable">
    <thead>
        <tr>
            <th>Nome</th>
            <th>CPF</th>
            <th>Data aniversário</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Any())
        {
            foreach (FCamara_Test.Dtos.AniversarianteDTO aniversariante in Model)
            {
                <tr>
                    <td>@aniversariante.Nome</td>
                    <td>@aniversariante.Cpf</td>
                    <td>@aniversariante.DataNascimento.ToString("g")</td>
                </tr>

            }
        }
        else
        {
            <tr><td colspan="3">Nenhum registro  encontrado</td></tr>
        }

    </tbody>
</table>

FCamara-Test/Views/Funcionario/CadastroFeitoComSucesso.cshtml
@{
    ViewData["Title"] = "Sucesso!";
}

<div class="content">

    <div class="lista-botoes">
        <a class="botao" asp-action="Index" asp-controller="Funcionario">Voltar</a>
    </div>

    <br />

    <div class="mensagem-sucesso">
        <span>Cadastro feito com sucesso!</span>
    </div>

</div>

FCamara-Test/Views/Funcionario/EditadoComSucesso.cshtml
@{
    ViewData["Title"] = "Editado!";
}

<div class="content">

    <div class="lista-botoes">
        <a class="botao" asp-action="Index" asp-controller="Funcionario">Voltar</a>
    </div>

    <br />

    <div class="mensagem-sucesso">
        <span>Editado com sucesso!</span>
    </div>

</div>

FCamara-Test/Views/Funcionario/Editar.cshtml
@model Funcionario
@{
    ViewData["Title"] = "Editar Funcionário";
}

<div class="content">

    <div class="lista-botoes">
        <a class="botao" asp-action="Index" asp-controller="Funcionario">Voltar</a>
    </div>

    <br />
    <h1>Editar funcionário</h1>

    <div>
        <form asp-action="EditarFuncionario" asp-controller="Funcionario">
            <fieldset>
                <legend>Dados do funcionário:</legend>
                <div class="box-form">

                    <input type="hidden" asp-for="Id" />

                    <div class="filtro">

                        <div class="box-campo">
                            <label>Nome do funcionário</label>
                            <input type="text" asp-for="Nome" class="campo-texto" />
                        </div>

                        <div class="box-campo">
                            <label>CPF do funcionário</label>
                            <input type="text" asp-for="CPF" class="campo-texto" />
                        </div>

                        <div class="box-campo">
                            <label>Data de nascimento</label>
                            <input type="text" asp-for="DataNascimento" class="campo-texto" />
                        </div>

                        <div class="box-campo">
                            <label>Sexo</label>
                            <select class="campo-texto" asp-for="Sexo">
                                <option value="0">Selecione</option>
                                <option value="F">F</option>
                                <option value="M">M</option>
                            </select>
                        </div>
                    </div>

                    <div class="filtro">
                        <div class="box-campo">
                            <label>CEP</label>
                            <input type="text" onblur="buscarCep(this.value)" asp-for="Cep" class="campo-texto" />
                        </div>

                        <div class="box-campo">
                            <label>Endereço</label>
                            <input type="text" asp-for="Endereco" class="campo-texto" />
                        </div>

                        <div class="box-campo">
                            <label>Bairro</label>
                            <input type="text" asp-for="Bairro" class="campo-texto" />
                        </div>

                        <div class="box-campo">
                            <label>Número</label>
                            <input type="text" asp-for="Numero" class="campo-texto" />
                        </div>

                    </div>

                    <div class="filtro">
                        <div class="box-campo">

                            <div class="box-campo">
                                <label>Complemento</label>
                                <input type="text" asp-for="Complemento" class="campo-texto" />
                            </div>

                            <div class="box-campo">
                                <label>Estado</label>
                                <input type="text" asp-for="Estado" class="campo-texto" />
                            </div>

                            <div class="box-campo">
                                <label>Cidade</label>
                                <input type="text" asp-for="Cidade" class="campo-texto" />
                            </div>
                        </div>

                    </div>

                </div>

                <div>
                    <button class="botao" style="width:100%;">Editar</button>
                </div>

            </fieldset>
        </form>
    </div>


</div>

FCamara-Test/Views/Funcionario/ExcluidoComSucesso.cshtml
@{
    ViewData["Title"] = "Excluido!";
}

<div class="content">

    <div class="lista-botoes">
        <a class="botao" asp-action="Index" asp-controller="Funcionario">Voltar</a>
    </div>

    <br />

    <div class="mensagem-sucesso">
        <span>Excluido com sucesso!</span>
    </div>

</div>

FCamara-Test/Views/Funcionario/Index.cshtml
@{
    ViewData["Title"] = "Funcionários";
}

<div class="content">

    <div class="lista-botoes">
        <a class="botao" asp-action="Novo" asp-controller="Funcionario">Adicionar novo funcionário</a>
    </div>

    <br />
    <h1>Listagem de funcionários</h1>

    <div>
        <form>
            <div class="box-form">

                <div class="filtro">

                    <div class="box-campo">
                        <label>Nome do funcionário</label>
                        <input type="text" id="nome" class="campo-texto" />
                    </div>

                    <div class="box-campo">
                        <label>Sexo</label>
                        <select class="campo-texto" id="sexo">
                            <option value="ambos">Ambos</option>
                            <option value="F">F</option>
                            <option value="M">M</option>
                        </select>
                    </div>

                    <div class="box-campo">
                        <label> Ativo</label>
                        <select class="campo-combo" id="ativo">
                            <option value="ambos">Ambos</option>
                            <option value="1">Sim</option>
                            <option value="0">Não</option>
                        </select>
                    </div>

                    <div class="box-campo">
                        <label>
                            Exibir apenas os funcionários que não possuem
                            dependentes.
                        </label>
                        <select class="campo-combo" id="naoPossuemDependencias">
                            <option selected="selected" value="0">Não</option>
                            <option value="1">Sim</option>
                        </select>
                    </div>

                </div>

                <div class="filtro-botao">
                    <div class="conteudo-filtro-botao">
                        <a class="botao" style="padding: 10px;" onclick="buscarFuncionarios()" >Buscar</a>
                    </div>
                </div>
            </div>

        </form>
    </div>

    <div id="partialListagemFuncionarios"></div>

</div>

FCamara-Test/Views/Funcionario/ListagemFuncionarios.cshtml
@model List<Funcionario>

<table class="rTable">
    <thead>
        <tr>
            <th>Nome</th>
            <th>CPF</th>
            <th>Sexo</th>
            <th>Status</th>
            <th>Ações</th>
        </tr>
    </thead>

    <tbody>

        @if (Model != null && Model.Any())
        {
            foreach (Funcionario funcionario in Model)
            {
                <tr>
                    <td>@funcionario.Nome</td>
                    <td>@funcionario.CPF</td>
                    <td>@funcionario.Sexo</td>
                    <td>@(funcionario.Ativo ? "Ativo" : "Inativo")</td>
                    <td>
                        <a class="botao" asp-route-id="@funcionario.Id" asp-action="MostrarDependentes" asp-controller="Funcionario">Dependentes</a>
                        <a class="botao" asp-route-id="@funcionario.Id" asp-action="NovoDependente" asp-controller="Funcionario">Novo dependente</a>
                        <a class="botao" asp-route-id="@funcionario.Id" asp-action="Editar" asp-controller="Funcionario">Editar</a>
                        <a class="botao excluir" asp-route-id="@funcionario.Id" asp-action="Excluir" asp-controller="Funcionario">Excluir</a>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr><td colspan="5">Nenhum registro  encontrado</td></tr>
        }

    </tbody>
</table>

FCamara-Test/Views/Funcionario/MostrarDependentes.cshtml
@model List<DependenteFuncionario>
@{
    ViewData["Title"] = "Dependentes";
}

<div class="content">

    <div class="lista-botoes">
        <a class="botao" asp-action="Index" asp-controller="Funcionario">Voltar</a>
    </div>


    <h1>Listagem de dependentes</h1>

    <table class="rTable">
        <thead>
            <tr>
                <th>Nome</th>
                <th>CPF</th>
                <th>Sexo</th>
                <th>Data Nascimento</th>
            </tr>
        </thead>

        <tbody>

            @if (Model != null && Model.Any())
            {
                foreach (DependenteFuncionario dependenteFuncionario in Model)
                {
                    <tr>
                        <td>@dependenteFuncionario.Nome</td>
                        <td>@dependenteFuncionario.CPF</td>
                        <td>@dependenteFuncionario.Sexo</td>
                        <td>@dependenteFuncionario.DataNascimento.Date.ToString("g")</td>
                    </tr>
                }
            }
            else
            {
                <tr><td colspan="5">Nenhum registro  encontrado</td></tr>
            }

        </tbody>
    </table>

</div>

FCamara-Test/Views/Funcionario/Novo.cshtml
@model Funcionario
@{
    ViewData["Title"] = "Novo Funcionário";
}

<div class="content">

    <div class="lista-botoes">
        <a class="botao" asp-action="Index" asp-controller="Funcionario">Voltar</a>
    </div>

    <br />
    <h1>Cadastro de funcionário</h1>

    @if (!string.IsNullOrEmpty(ViewBag.Erro))
    {
        <div class="mensagem-erro">
            <span>@ViewBag.Erro</span>
        </div>
    }

    <div>
        <form asp-action="CadastrarFuncionario" asp-controller="Funcionario">
            <fieldset>
                <legend>Dados do funcionário:</legend>
                <div class="box-form">

                    <div class="filtro">

                        <div class="box-campo">
                            <label>Nome do funcionário</label>
                            <input type="text" asp-for="Nome" class="campo-texto" />
                        </div>

                        <div class="box-campo">
                            <label>CPF do funcionário</label>
                            <input type="text" asp-for="CPF" class="campo-texto" />
                        </div>

                        <div class="box-campo">
                            <label>Data de nascimento</label>
                            <input type="text" asp-for="DataNascimento" class="campo-texto" />
                        </div>

                        <div class="box-campo">
                            <label>Sexo</label>
                            <select class="campo-texto" asp-for="Sexo">
                                <option value="0">Selecione</option>
                                <option value="F">F</option>
                                <option value="M">M</option>
                            </select>
                        </div>
                    </div>

                    <div class="filtro">
                        <div class="box-campo">
                            <label>CEP</label>
                            <input type="text" onblur="buscarCep(this.value)" asp-for="Cep" class="campo-texto" />
                        </div>

                        <div class="box-campo">
                            <label>Endereço</label>
                            <input type="text" asp-for="Endereco" class="campo-texto" />
                        </div>

                        <div class="box-campo">
                            <label>Bairro</label>
                            <input type="text" asp-for="Bairro" class="campo-texto" />
                        </div>

                        <div class="box-campo">
                            <label>Número</label>
                            <input type="text" asp-for="Numero" class="campo-texto" />
                        </div>

                    </div>

                    <div class="filtro">
                        <div class="box-campo">

                            <div class="box-campo">
                                <label>Complemento</label>
                                <input type="text" asp-for="Complemento" class="campo-texto" />
                            </div>

                            <div class="box-campo">
                                <label>Estado</label>
                                <input type="text" asp-for="Estado" class="campo-texto" />
                            </div>

                            <div class="box-campo">
                                <label>Cidade</label>
                                <input type="text" asp-for="Cidade" class="campo-texto" />
                            </div>
                        </div>

                    </div>

                </div>

                <div>
                    <button class="botao" style="width:100%;">Cadastrar</button>
                </div>

            </fieldset>
        </form>
    </div>


</div>

FCamara-Test/Views/Funcionario/NovoDependente.cshtml
@model DependenteFuncionario
@{
    ViewData["Title"] = "Novo Funcionário";
}

<div class="content">

    <div class="lista-botoes">
        <a class="botao" asp-action="Index" asp-controller="Funcionario">Voltar</a>
    </div>

    <br />
    <h1>Cadastro de dependente</h1>

    @if (!string.IsNullOrEmpty(ViewBag.Erro))
    {
        <div class="mensagem-erro">
            <span>@ViewBag.Erro</span>
        </div>
    }

    <div>
        <form asp-action="CadastrarDependenteFuncionario" asp-controller="Funcionario">
            <fieldset>
                <legend>Dados do dependente:</legend>
                <div class="box-form">

                    <input type="hidden" asp-for="FuncionarioId" class="campo-texto" />

                    <div class="filtro">

                        <div class="box-campo">
                            <label>Nome do funcionário</label>
                            <input type="text" asp-for="Nome" class="campo-texto" />
                        </div>

                        <div class="box-campo">
                            <label>CPF do funcionário</label>
                            <input type="text" asp-for="CPF" class="campo-texto" />
                        </div>

                    </div>


                    <div class="filtro">
                        <div class="box-campo">
                            <label>Data de nascimento</label>
                            <input type="text" asp-for="DataNascimento" class="campo-texto" />
                        </div>

                        <div class="box-campo">
                            <label>Sexo</label>
                            <select class="campo-texto" asp-for="Sexo">
                                <option value="0">Selecione</option>
                                <option value="F">F</option>
                                <option value="M">M</option>
                            </select>
                        </div>
                    </div>

                </div>

                <div>
                    <button class="botao" style="width:100%;">Cadastrar</button>
                </div>
            </fieldset>
        </form>
    </div>


</div>

FCamara-Test/Views/Log/Index.cshtml
@using Newtonsoft.Json;
@model List<HistoricoAuditoria>
@{
    ViewData["Title"] = "Logs";
}

<div class="content">

    <h1>Listagem de logs</h1>

    <table class="rTable">
        <thead>
            <tr>
                <th>Funcionalidade</th>
                <th>Identificador da funcionalidade</th>
                <th>Ação</th>
                <th>Data cadastro</th>
                <th>Conteudo</th>
            </tr>
        </thead>

        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (HistoricoAuditoria historicoAuditoria in Model)
                {
                    <tr>
                        <td>@historicoAuditoria.Funcionalidade</td>
                        <td>@historicoAuditoria.IdentificadorFuncionalidade</td>
                        <td>@historicoAuditoria.Evento</td>
                        <td>@historicoAuditoria.DataCadastro.ToString("g")</td>
                        <td>
                            @historicoAuditoria.Dados
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr><td colspan="4">Nenhum registro  encontrado</td></tr>
            }
        </tbody>
    </table>


</div>

FCamara-Test/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FCamara/Toledo - Teste Leonardo</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <ul class="menu">
            <li><a asp-action="Index" asp-controller="Funcionario">Funcionários</a></li>
            <li><a asp-action="Index" asp-controller="Aniversariante">Aniversariantes</a></li>
            <li><a asp-action="Index" asp-controller="Log">Logs</a></li>
        </ul>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="rodape">
        <div class="rodape-conteudo">
            &copy; 2021 - FCamara/Toledo - Teste Leonardo
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/jquery.mask.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>